### ISSUE TITLE
How can we specify by command line parameter that Nuget should be used as the source?

### ISSUE THREAD

**Issue by schittli** [Apteco/AptecoPSModules#22]
Hello

**thank you very much for sharing your great work!**
It is a shame that we customers bring Microsoft a profit of 1500 million US$ every month, but M$ is not interested in providing basic functions properly and professionally.

**I have a very basic question:**
There are packages that were first published on PSGallery and later in NuGet, e.g. `Newtonsoft.Json`.

How can we specify that `Install-Dependencies` should use NuGet so that the right / latest version of a Module / Package gets installed?

Thanks a lot, kind regards,
Thomas

**Comment by gitfvb** [comment]
Hi @schittli , thanks. PSGallery is connected to Scripts and Modules where NuGet is tied to packages (global/local). So you need to use the right parameter to pick the right repository. I hope that answers your question.
